# -*- coding: utf-8 -*-
"""ai_video_enhancement_ULTIMATE.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1A0-VyEX8D1e-Cz8j2G8gK5W_eqCKeNuj

# 🎬 AI Video Enhancement Pipeline — Ultimate Edition
> Merged from `enhance.py` (GFPGAN + parallel CPU) + our pipeline (filters + metrics + APIs)

**What's new vs Final Edition:**
- ✅ **GFPGAN face restoration** — 2nd AI pass for faces (from enhance.py)
- ✅ **Parallel CPU mode** — uses all cores when no GPU (from enhance.py)
- ✅ **tqdm progress bars** per frame (from enhance.py)
- ✅ **`-movflags +faststart`** — instant web streaming in FFmpeg output
- ✅ **CRF 18** encode quality (up from 23)
- ✅ **Batch directory processing** — drop a folder, process all videos
- ✅ **Skip flags** — skip SR or face restore independently
- ✅ **Torchvision warning suppressor** baked in
- ✅ All our stages kept: classical filters, quality metrics, APIs, CDN, manifest

---
## 📦 SECTION 0 — Install & Compatibility
"""

!pip install torch torchvision

import warnings
# Silence torchvision deprecation noise (from enhance.py)
warnings.filterwarnings('ignore', category=UserWarning, module='torchvision.*')

# Fix torchvision version conflict with Real-ESRGAN
#!pip install torchvision==0.16.0 --index-url https://download.pytorch.org/whl/cu118 -q
#!pip install torch==2.1.0 --index-url https://download.pytorch.org/whl/cu118 -q

# Core
!pip install opencv-python-headless ffmpeg-python imageio Pillow numpy tqdm -q

# AI models
!pip install basicsr realesrgan gfpgan -q

# Metrics
!pip install piq lpips -q

# APIs & storage
!pip install replicate requests boto3 -q

# Job queue
!pip install rq redis -q

print('✅ All dependencies installed')

"""### ⬇️ Auto-Download Model Weights (cached — skips if already present)"""

from pathlib import Path

Path('weights').mkdir(exist_ok=True)

WEIGHTS = {
    'RealESRGAN_x4plus.pth': 'https://github.com/xinntao/Real-ESRGAN/releases/download/v0.1.0/RealESRGAN_x4plus.pth',
    'RealESRGAN_x2plus.pth': 'https://github.com/xinntao/Real-ESRGAN/releases/download/v0.2.1/RealESRGAN_x2plus.pth',
    'GFPGANv1.4.pth':        'https://github.com/TencentARC/GFPGAN/releases/download/v1.3.0/GFPGANv1.4.pth',
}

for filename, url in WEIGHTS.items():
    dest = Path('weights') / filename
    if dest.exists():
        print(f'✅ Already exists: {filename}')
    else:
        print(f'⬇️  Downloading {filename}...')
        import subprocess
        subprocess.run(['wget', '-q', '--show-progress', '-O', str(dest), url])
        print(f'✅ Downloaded: {filename}')

"""---
## ⚙️ SECTION 1 — Global Config & Setup
"""

import warnings
warnings.filterwarnings('ignore', category=UserWarning, module='torchvision.*')

import os, uuid, shutil, json, subprocess
from pathlib import Path
from multiprocessing import cpu_count
import torch
import cv2
import numpy as np

# ── Directories ──────────────────────────────────────────────────────
UPLOAD_DIR  = Path('pipeline/uploads')
WORK_DIR    = Path('pipeline/working')
OUTPUT_DIR  = Path('pipeline/outputs')
WEIGHTS_DIR = Path('weights')
for d in [UPLOAD_DIR, WORK_DIR, OUTPUT_DIR, WEIGHTS_DIR]:
    d.mkdir(parents=True, exist_ok=True)

# ── Hardware detection ────────────────────────────────────────────────
USE_GPU      = torch.cuda.is_available()
DEVICE       = torch.device('cuda') if USE_GPU else torch.device('cpu')
NUM_CPU_CORES = cpu_count()

if USE_GPU:
    print(f'✅ GPU detected: {torch.cuda.get_device_name(0)} — running GPU mode')
else:
    print(f'⚠️  No GPU — will use parallel CPU mode ({NUM_CPU_CORES} cores)')

# ── Model config (from enhance.py) ────────────────────────────────────
REALESRGAN_MODEL = 'RealESRGAN_x4plus'
GFPGAN_VERSION   = '1.4'
UPSCALE_RATIO    = 4
ALLOWED_EXTS     = {'.mp4', '.mov', '.webm', '.avi', '.mkv'}
MAX_FILE_MB      = 500

print(f'🔧 Config ready | cores={NUM_CPU_CORES} | upscale={UPSCALE_RATIO}x')

"""---
## 📤 STAGE 2 — Upload (single file or batch directory)
"""

def upload_video(source_path: str) -> dict:
    """Single file upload."""
    src = Path(source_path)
    assert src.exists(), f'File not found: {src}'
    assert src.suffix.lower() in ALLOWED_EXTS, f'Unsupported: {src.suffix}'
    size_mb = src.stat().st_size / (1024**2)
    assert size_mb <= MAX_FILE_MB, f'Too large: {size_mb:.1f} MB'
    job_id = str(uuid.uuid4())[:8]
    dest   = UPLOAD_DIR / f'{job_id}{src.suffix}'
    shutil.copy2(src, dest)
    print(f'✅ Uploaded | job_id={job_id} | size={size_mb:.2f} MB')
    return {'job_id': job_id, 'path': str(dest), 'size_mb': round(size_mb,2)}

def upload_batch(directory: str) -> list:
    """Batch upload — from enhance.py idea. Returns list of jobs."""
    d = Path(directory)
    assert d.is_dir(), f'Not a directory: {d}'
    files = [f for f in d.iterdir() if f.suffix.lower() in ALLOWED_EXTS]
    assert files, f'No supported video files in {d}'
    print(f'📂 Found {len(files)} video(s) in {d}')
    return [upload_video(str(f)) for f in sorted(files)]
job = upload_video('test2.mp4')
# Batch:   jobs = upload_batch('my_videos_folder/')

"""---
## 🎞️ STAGE 3 — Video Preprocessor
"""

import ffmpeg
from fractions import Fraction  # safe fps parsing (no eval)

def get_video_fps(video_path: str) -> str:
    """Safe FPS detection using Fraction instead of eval() (security fix vs enhance.py)."""
    try:
        cmd = ['ffprobe','-v','error','-select_streams','v:0',
               '-show_entries','stream=r_frame_rate',
               '-of','default=noprint_wrappers=1:nokey=1', str(video_path)]
        result = subprocess.run(cmd, capture_output=True, text=True, check=True)
        fps = float(Fraction(result.stdout.strip()))
        return str(round(fps, 3))
    except Exception:
        return '30'

def preprocess_video(job: dict) -> dict:
    src  = job['path']
    jid  = job['job_id']
    wdir = WORK_DIR / jid
    wdir.mkdir(parents=True, exist_ok=True)

    probe = ffmpeg.probe(src)
    vs    = next(s for s in probe['streams'] if s['codec_type'] == 'video')
    fps   = get_video_fps(src)
    meta  = {
        'width':    int(vs['width']),
        'height':   int(vs['height']),
        'fps':      float(fps),
        'duration': float(probe['format'].get('duration', 0)),
        'bitrate':  int(probe['format'].get('bit_rate', 0)) // 1000,
        'codec':    vs['codec_name'],
    }
    with open(wdir / 'metadata.json', 'w') as f:
        json.dump(meta, f, indent=2)

    frames_dir = wdir / 'frames'
    frames_dir.mkdir(exist_ok=True)
    # Use frame_%06d like enhance.py (supports more frames than %05d)
    (ffmpeg.input(src)
     .output(str(frames_dir / 'frame_%06d.png'))
     .run(quiet=True, overwrite_output=True))

    audio_path = str(wdir / 'audio.aac')
    try:
        ffmpeg.input(src).output(audio_path, acodec='copy').run(quiet=True, overwrite_output=True)
    except ffmpeg.Error:
        audio_path = None

    frame_count = len(list(frames_dir.glob('*.png')))
    print(f'✅ Preprocessed | {frame_count} frames | {meta["width"]}x{meta["height"]} @ {fps}fps')
    return {**job, 'meta': meta, 'fps': fps, 'frames_dir': str(frames_dir),
            'audio_path': audio_path, 'frame_count': frame_count, 'work_dir': str(wdir)}

job = preprocess_video(job)

"""---
## 🔍 STAGE 4 — Quality Analyzer
Blur · Noise · Low-light · Artifacts → smart routing
"""

def estimate_blur(frame):
    return cv2.Laplacian(cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY), cv2.CV_64F).var()

def estimate_noise(frame):
    gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY).astype(np.float32)
    return float(np.abs(gray - cv2.GaussianBlur(gray,(5,5),0)).mean())

def detect_low_light(frame):
    return float(cv2.cvtColor(frame, cv2.COLOR_BGR2HSV)[:,:,2].mean()) < 60

def detect_faces(frame) -> bool:
    """Detect if video contains faces — gates GFPGAN usage."""
    detector = cv2.CascadeClassifier(cv2.data.haarcascades + 'haarcascade_frontalface_default.xml')
    gray     = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
    faces    = detector.detectMultiScale(gray, 1.1, 4)
    return len(faces) > 0

def analyze_quality(job: dict, sample_frames: int = 10) -> dict:
    frame_files = sorted(Path(job['frames_dir']).glob('*.png'))
    step = max(1, len(frame_files) // sample_frames)
    sampled = frame_files[::step][:sample_frames]
    blurs, noises, low_lights, has_faces = [], [], [], []
    for fp in sampled:
        frame = cv2.imread(str(fp))
        if frame is None: continue
        blurs.append(estimate_blur(frame))
        noises.append(estimate_noise(frame))
        low_lights.append(detect_low_light(frame))
        has_faces.append(detect_faces(frame))
    quality = {
        'blur_score':      round(float(np.mean(blurs)), 2),
        'noise_score':     round(float(np.mean(noises)), 2),
        'low_light_pct':   round(sum(low_lights)/len(low_lights)*100, 1),
        'faces_detected':  any(has_faces),   # gates GFPGAN
        'needs_denoise':   float(np.mean(noises)) > 3.0,
        'needs_deblur':    float(np.mean(blurs)) < 200.0,
        'needs_color_fix': sum(low_lights)/len(low_lights) > 0.2,
        'needs_sr':        job['meta']['width'] < 1080,
    }
    quality['recommended_filter'] = (
        'denoise' if quality['needs_denoise'] else 'balanced'
    )
    print('🔍 Quality Report:')
    for k, v in quality.items(): print(f'   {k:25s}: {v}')
    return {**job, 'quality': quality}

job = analyze_quality(job)

"""---
## 🎛️ STAGE 5 — Classical Filter Enhancement
Median · Bilateral · Gaussian · Unsharp Mask — runs before SR for cleaner input
"""

from tqdm import tqdm

def apply_filter_enhancement(frame, mode='balanced'):
    if mode == 'artifact':
        return cv2.medianBlur(frame, ksize=3)
    elif mode == 'denoise':
        return cv2.bilateralFilter(frame, d=9, sigmaColor=75, sigmaSpace=75)
    elif mode == 'smooth':
        blur = cv2.GaussianBlur(frame, (5,5), 0)
        return cv2.addWeighted(frame, 1.5, blur, -0.5, 0)
    elif mode == 'balanced':
        clean = cv2.bilateralFilter(frame, d=7, sigmaColor=50, sigmaSpace=50)
        blur  = cv2.GaussianBlur(clean, (0,0), 3)
        return cv2.addWeighted(clean, 1.4, blur, -0.4, 0)
    elif mode == 'aggressive':
        s1 = cv2.medianBlur(frame, 3)
        s2 = cv2.bilateralFilter(s1, d=9, sigmaColor=75, sigmaSpace=75)
        blur = cv2.GaussianBlur(s2, (0,0), 3)
        return cv2.addWeighted(s2, 1.5, blur, -0.5, 0)
    return frame

def run_filter_stage(job, filter_mode=None) -> dict:
    if filter_mode is None:
        filter_mode = job['quality'].get('recommended_filter', 'balanced')
        print(f'🤖 Auto-selected filter: {filter_mode}')
    frames_dir  = Path(job['frames_dir'])
    out_dir     = Path(job['work_dir']) / 'filtered_frames'
    out_dir.mkdir(exist_ok=True)
    frame_files = sorted(frames_dir.glob('*.png'))
    for fp in tqdm(frame_files, desc=f'Filter [{filter_mode}]'):
        frame = cv2.imread(str(fp))
        if frame is None: continue
        cv2.imwrite(str(out_dir / fp.name), apply_filter_enhancement(frame, filter_mode))
    print(f'✅ Filter done | mode={filter_mode} | {len(frame_files)} frames')
    job['frames_dir'] = str(out_dir)
    return {**job, 'filter_mode': filter_mode}

job = run_filter_stage(job)  # auto-mode
# job = run_filter_stage(job, filter_mode='balanced')

"""---
## 🤖 STAGE 6 — AI Enhancement Engine
**Real-ESRGAN** (SR 2x/4x) + **GFPGAN** (face restoration) — GPU or parallel CPU
"""

file_path = "/usr/local/lib/python3.12/dist-packages/basicsr/data/degradations.py"

with open(file_path, "r") as f:
    content = f.read()

content = content.replace(
    "from torchvision.transforms.functional_tensor import rgb_to_grayscale",
    "from torchvision.transforms.functional import rgb_to_grayscale"
)

with open(file_path, "w") as f:
    f.write(content)

print("Patched:", file_path)

!grep -n "rgb_to_grayscale" /usr/local/lib/python3.12/dist-packages/basicsr/data/degradations.py

from tqdm import tqdm
from multiprocessing import Pool
from torchvision.transforms.functional import rgb_to_grayscale
# ── Model loaders ─────────────────────────────────────────────────────
def load_realesrgan(scale=4):
    from realesrgan import RealESRGANer
    from basicsr.archs.rrdbnet_arch import RRDBNet
    model = RRDBNet(num_in_ch=3, num_out_ch=3, num_feat=64,
                    num_block=23, num_grow_ch=32, scale=scale)
    weight = str(WEIGHTS_DIR / f'RealESRGAN_x{scale}plus.pth')
    return RealESRGANer(scale=scale, model_path=weight, model=model,
                        tile=512, tile_pad=10,
                        half=(DEVICE.type=='cuda'), device=DEVICE)

def load_gfpgan(upsampler=None):
    """GFPGAN face restorer — from enhance.py. Uses SR as background upsampler."""
    from gfpgan import GFPGANer
    weight = str(WEIGHTS_DIR / f'GFPGANv{GFPGAN_VERSION}.pth')
    return GFPGANer(
        model_path=weight,
        upscale=UPSCALE_RATIO,
        arch='clean',
        channel_multiplier=2,
        bg_upsampler=upsampler,  # SR handles background, GFPGAN handles faces
        device=DEVICE
    )

# ── Parallel CPU workers (from enhance.py) ────────────────────────────
_worker_upsampler = None
_worker_face_enh  = None

def _init_worker(scale, run_face):
    global _worker_upsampler, _worker_face_enh
    _worker_upsampler = load_realesrgan(scale)
    if run_face:
        _worker_face_enh = load_gfpgan(upsampler=None)  # no bg_upsampler in parallel

def _worker_process_frame(args):
    fp, out_path, run_sr, run_face = args
    img = cv2.imread(fp, cv2.IMREAD_UNCHANGED)
    if img is None: return False
    try:
        if run_sr and _worker_upsampler:
            img, _ = _worker_upsampler.enhance(img, outscale=UPSCALE_RATIO)
        if run_face and _worker_face_enh:
            _, _, img = _worker_face_enh.enhance(img, has_aligned=False,
                                                  only_center_face=False, paste_back=True)
        cv2.imwrite(out_path, img)
        return True
    except Exception as e:
        print(f'Worker error on {fp}: {e}')
        return False

# ── Main enhancement orchestrator ─────────────────────────────────────
def run_enhancement_engine(
    job,
    enhance_mode    = 'hd',    # 'fast'|'hd'|'ultra'
    skip_sr         = False,   # skip Real-ESRGAN
    skip_face       = False,   # skip GFPGAN
    enable_parallel = True,    # use multiprocessing on CPU
) -> dict:
    quality    = job['quality']
    frames_dir = Path(job['frames_dir'])
    out_dir    = Path(job['work_dir']) / 'enhanced_frames'
    out_dir.mkdir(exist_ok=True)
    frame_files = sorted(frames_dir.glob('*.png'))

    run_sr   = (not skip_sr) and quality['needs_sr'] and enhance_mode != 'fast'
    run_face = (not skip_face) and quality['faces_detected']
    scale    = 4 if enhance_mode == 'ultra' else 2

    print(f'🤖 Enhancement | SR={run_sr} | GFPGAN={run_face} | parallel={not USE_GPU and enable_parallel}')

    if USE_GPU:
        # ── Single-threaded GPU path ──────────────────────────────────
        upsampler    = load_realesrgan(scale) if run_sr else None
        face_enhance = load_gfpgan(upsampler) if run_face else None
        if upsampler:    print('✅ Real-ESRGAN loaded')
        if face_enhance: print('✅ GFPGAN loaded')

        for fp in tqdm(frame_files, desc='Enhancing (GPU)'):
            img = cv2.imread(str(fp), cv2.IMREAD_UNCHANGED)
            if img is None: continue
            try:
                if upsampler:
                    img, _ = upsampler.enhance(img, outscale=UPSCALE_RATIO)
                if face_enhance:
                    _, _, img = face_enhance.enhance(
                        img, has_aligned=False, only_center_face=False, paste_back=True)
                cv2.imwrite(str(out_dir / fp.name), img)
            except Exception as e:
                print(f'Error on {fp.name}: {e} — copying original')
                shutil.copy2(str(fp), str(out_dir / fp.name))

    elif enable_parallel:
        # ── Parallel CPU path (from enhance.py) ───────────────────────
        tasks = [(str(fp), str(out_dir / fp.name), run_sr, run_face)
                 for fp in frame_files]
        with Pool(processes=NUM_CPU_CORES,
                  initializer=_init_worker,
                  initargs=(scale, run_face)) as pool:
            list(tqdm(pool.imap(_worker_process_frame, tasks),
                      total=len(tasks), desc='Enhancing (parallel CPU)'))
    else:
        # ── Single-threaded CPU fallback ──────────────────────────────
        upsampler = load_realesrgan(scale) if run_sr else None
        for fp in tqdm(frame_files, desc='Enhancing (CPU)'):
            img = cv2.imread(str(fp))
            if img is None: continue
            if upsampler: img, _ = upsampler.enhance(img, outscale=UPSCALE_RATIO)
            cv2.imwrite(str(out_dir / fp.name), img)

    print(f'✅ Enhancement done | {len(frame_files)} frames')
    return {**job, 'enhanced_frames_dir': str(out_dir),
            'enhance_mode': enhance_mode, 'ran_gfpgan': run_face}

job = run_enhancement_engine(job, enhance_mode='hd')
job = run_enhancement_engine(job, skip_face=True)   # no face restore
# job = run_enhancement_engine(job, skip_sr=True)     # face only

"""---
## 🌐 STAGE 7 — External API Fallbacks
Replicate · DeepAI · Cloudinary — activate by filling keys
"""

!pip install replicate -q

import os
import requests

REPLICATE_API_TOKEN = os.environ.get('REPLICATE_API_TOKEN', '')   # replicate.com/account
DEEPAI_API_KEY      = os.environ.get('DEEPAI_API_KEY', '')        # deepai.org/dashboard
#CLOUDINARY_URL      = 'cloudinary://key:secret@cloud_name'



def enhance_frame_replicate(frame_path: str, scale: int = 4) -> str:
    """Cloud Real-ESRGAN via Replicate."""
    import replicate

    os.environ["REPLICATE_API_TOKEN"] = REPLICATE_API_TOKEN

    with open(frame_path, "rb") as f:
        output = replicate.run(
            "nightmareai/real-esrgan:42fed1c4974146d4d2414e2be2c5277c7fcf05fcc3a73abf41610695738c1d7b",
            input={
                "image": f,
                "scale": scale,
                "face_enhance": False
            }
        )

    # Replicate output may be a string URL or list
    if isinstance(output, list):
        output_url = output[0]
    else:
        output_url = output

    out_path = frame_path.rsplit(".", 1)[0] + "_sr.png"

    response = requests.get(output_url)
    response.raise_for_status()

    with open(out_path, "wb") as f:
        f.write(response.content)

    return out_path


def enhance_frame_deepai(frame_path: str) -> str:
    """DeepAI Waifu2x fallback."""
    with open(frame_path, "rb") as f:
        r = requests.post(
            "https://api.deepai.org/api/waifu2x",
            files={"image": f},
            headers={"api-key": DEEPAI_API_KEY}
        )

    result = r.json()

    if "output_url" not in result:
        raise ValueError(f"DeepAI error: {result}")

    out_path = frame_path.rsplit(".", 1)[0] + "_deepai.png"

    response = requests.get(result["output_url"])
    response.raise_for_status()

    with open(out_path, "wb") as f:
        f.write(response.content)

    return out_path


print("✅ API integrations ready")

"""---
## 🔧 STAGE 8 — Post-Processing
Reassemble + audio sync → H.264/H.265/AV1 → CRF 18 + `-movflags +faststart` (web-ready)
"""

def post_process(job, codec='h264', target_res='1080p') -> dict:
    CODEC_MAP      = {'h264':'libx264','h265':'libx265','av1':'libaom-av1'}
    RESOLUTION_MAP = {'720p':(1280,720),'1080p':(1920,1080),'4k':(3840,2160)}

    enh_dir    = Path(job['enhanced_frames_dir'])
    # frame pattern — supports both %05d and %06d
    frames_glob = str(enh_dir / 'frame_%06d.png')
    if not list(enh_dir.glob('frame_??????.png')):
        frames_glob = str(enh_dir / 'frame_%05d.png')

    audio_path = job.get('audio_path')
    out_path   = str(OUTPUT_DIR / f"{job['job_id']}_{target_res}_{codec}.mp4")
    w, h = RESOLUTION_MAP.get(target_res, (1920,1080))
    vf   = f'scale={w}:{h}:force_original_aspect_ratio=decrease,pad={w}:{h}:(ow-iw)/2:(oh-ih)/2'
    fps  = job.get('fps', '30')

    # Build FFmpeg command (from enhance.py: +faststart, crf=18, pix_fmt)
    cmd = ['ffmpeg', '-y',
           '-framerate', str(fps),
           '-i', frames_glob]
    if audio_path and Path(audio_path).exists():
        cmd += ['-i', audio_path,
                '-map', '0:v:0', '-map', '1:a:0',
                '-c:a', 'aac', '-b:a', '192k']
    cmd += ['-c:v', CODEC_MAP[codec],
            '-crf', '18',           # Quality: 18 (vs old 23) — from enhance.py
            '-preset', 'fast',
            '-pix_fmt', 'yuv420p',  # Max compatibility
            '-vf', vf,
            '-movflags', '+faststart',  # Web streaming — from enhance.py
            out_path]
    subprocess.run(cmd, capture_output=True, check=True)

    size_mb = Path(out_path).stat().st_size / (1024**2)
    print(f'✅ Post-processed | {out_path} | {size_mb:.1f} MB | CRF18 + faststart')
    return {**job, 'output_path': out_path, 'output_res': target_res, 'codec': codec}

job = post_process(job, codec='h264', target_res='1080p')

"""---
## 👁️ STAGE 10 — Creator Preview
"""

import matplotlib.pyplot as plt

def generate_preview(job, n_frames=6):
    orig_files = sorted(Path(job['frames_dir']).glob('*.png'))
    enh_files  = sorted(Path(job['enhanced_frames_dir']).glob('*.png'))
    step = max(1, len(orig_files)//n_frames)
    indices = list(range(0, len(orig_files), step))[:n_frames]
    fig, axes = plt.subplots(2, n_frames, figsize=(n_frames*4, 8))
    gfpgan_tag = ' + GFPGAN' if job.get('ran_gfpgan') else ''
    fig.suptitle(
        f"Before / After | {job.get('enhance_mode','hd').upper()}{gfpgan_tag} "
        f"| Filter: {job.get('filter_mode','none').upper()}",
        fontsize=15, fontweight='bold'
    )
    for col, idx in enumerate(indices):
        orig = cv2.cvtColor(cv2.imread(str(orig_files[idx])), cv2.COLOR_BGR2RGB)
        enh  = cv2.cvtColor(cv2.imread(str(enh_files[min(idx,len(enh_files)-1)])), cv2.COLOR_BGR2RGB)
        axes[0,col].imshow(orig); axes[0,col].set_title(f'Before #{idx}'); axes[0,col].axis('off')
        axes[1,col].imshow(enh);  axes[1,col].set_title(f'After #{idx}');  axes[1,col].axis('off')
    axes[0,0].set_ylabel('ORIGINAL', fontsize=12, fontweight='bold')
    axes[1,0].set_ylabel('ENHANCED', fontsize=12, fontweight='bold')
    plt.tight_layout()
    out = str(OUTPUT_DIR / f"{job['job_id']}_preview.png")
    plt.savefig(out, dpi=120, bbox_inches='tight')
    plt.show()
    print(f'✅ Preview: {out}')

generate_preview(job)

"""---
## 📊 STAGE 11 — Quality Metrics
PSNR · SSIM · LPIPS · Flicker Score
"""

import torch

try:
    import piq
    PIQ_AVAILABLE = True
except ImportError:
    PIQ_AVAILABLE = False

try:
    import lpips
    LPIPS_FN = lpips.LPIPS(net='alex')
    LPIPS_AVAILABLE = True
except ImportError:
    LPIPS_AVAILABLE = False

def frame_to_tensor(frame):
    rgb = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB).astype(np.float32)/255.0
    return torch.from_numpy(rgb).permute(2,0,1).unsqueeze(0)

def compute_metrics(orig, enh):
    h = min(orig.shape[0],enh.shape[0]); w = min(orig.shape[1],enh.shape[1])
    o = frame_to_tensor(cv2.resize(orig,(w,h)))
    e = frame_to_tensor(cv2.resize(enh,(w,h)))
    r = {}
    if PIQ_AVAILABLE:
        r['psnr'] = round(piq.psnr(o,e,data_range=1.).item(),2)
        r['ssim'] = round(piq.ssim(o,e,data_range=1.).item(),4)
    if LPIPS_AVAILABLE:
        r['lpips'] = round(LPIPS_FN(o*2-1, e*2-1).item(),4)
    return r

def evaluate_quality(job, sample_n=10):
    orig_files = sorted(Path(job['frames_dir']).glob('*.png'))
    enh_files  = sorted(Path(job['enhanced_frames_dir']).glob('*.png'))
    step = max(1, len(orig_files)//sample_n)
    all_m, enh_frames = [], []
    for i in range(0, len(orig_files), step):
        o = cv2.imread(str(orig_files[i]))
        e = cv2.imread(str(enh_files[min(i,len(enh_files)-1)]))
        if o is None or e is None: continue
        all_m.append(compute_metrics(o, e))
        enh_frames.append(e)
    keys = all_m[0].keys() if all_m else []
    summary = {k: round(float(np.mean([m[k] for m in all_m])),4) for k in keys}
    if len(enh_frames) > 1:
        diffs = [np.abs(enh_frames[i].astype(float)-enh_frames[i-1].astype(float)).mean()
                 for i in range(1,len(enh_frames))]
        summary['flicker_score'] = round(float(np.mean(diffs)),4)
    print('📊 Quality Metrics:')
    for k,v in summary.items(): print(f'   {k:20s}: {v}')
    print('\n   PSNR↑  SSIM↑  LPIPS↓  Flicker↓')
    print(f'\n   VMAF cmd: ffmpeg -i {job["path"]} -i {job["output_path"]} -lavfi libvmaf -f null -')
    return {**job, 'metrics': summary}
job = evaluate_quality(job)

"""---
## 🚀 STAGE 12 — Publish Manifest
"""

def prepare_publish_manifest(job):
    manifest = {
        'job_id':       job['job_id'],
        'status':       'ready',
        'profiles':     {
            'mobile':  {'res':'720p',  'bitrate':'2M',  'codec':'h264'},
            'tablet':  {'res':'1080p', 'bitrate':'4M',  'codec':'h264'},
            'desktop': {'res':'1080p', 'bitrate':'8M',  'codec':'h265'},
            'tv_4k':   {'res':'4k',    'bitrate':'20M', 'codec':'av1'},
        },
        'cdn':          job.get('cdn_urls',{}),
        'metrics':      job.get('metrics',{}),
        'enhance_mode': job.get('enhance_mode'),
        'filter_mode':  job.get('filter_mode'),
        'ran_gfpgan':   job.get('ran_gfpgan', False),
        'original_res': f"{job['meta']['width']}x{job['meta']['height']}",
        'output_res':   job.get('output_res'),
    }
    path = OUTPUT_DIR / f"{job['job_id']}_manifest.json"
    with open(path,'w') as f: json.dump(manifest, f, indent=2)
    print(f'✅ Manifest -> {path}')
    print(json.dumps(manifest, indent=2))
    return {**job, 'manifest_path': str(path)}
job = prepare_publish_manifest(job)

"""---
## 🏁 FULL PIPELINE — Single File
All 12 stages in one call.
"""

import time

def full_pipeline(
    video_path,
    enhance_mode     = 'hd',    # 'fast' | 'hd' | 'ultra'
    filter_mode      = None,    # None=auto | 'balanced'|'artifact'|'denoise'|'aggressive'
    codec            = 'h264',
    target_res       = '1080p',
    skip_sr          = False,   # skip Real-ESRGAN
    skip_face        = False,   # skip GFPGAN face restoration
    dry_run_storage  = True,
    use_api_fallback = False,
):
    t0 = time.time()
    print('=' * 60)
    print('  AI Video Enhancement — Ultimate Edition')
    print(f'  {enhance_mode.upper()} | filter={filter_mode or "auto"} | {codec} | {target_res}')
    print(f'  SR={not skip_sr} | GFPGAN={not skip_face} | GPU={USE_GPU}')
    print('=' * 60)

    job = upload_video(video_path)
    job = preprocess_video(job)
    job = analyze_quality(job)
    job = run_filter_stage(job, filter_mode)
    job = run_enhancement_engine(job, enhance_mode=enhance_mode,
                                  skip_sr=skip_sr, skip_face=skip_face)
    job = post_process(job, codec=codec, target_res=target_res)
    #job = upload_to_storage(job, dry_run=dry_run_storage)
    generate_preview(job)
    job = evaluate_quality(job)
    job = prepare_publish_manifest(job)

    print(f'\n✅ Done in {time.time()-t0:.1f}s')
    print(f'   Output : {job.get("output_path")}')
    return job


# ════════════════════════════════════════════════════════════
# ▶  RUN — single file
# ════════════════════════════════════════════════════════════
result = full_pipeline(
    video_path       = 'test2.mp4',   # ← change this
    enhance_mode     = 'hd',
    filter_mode      = None,               # auto-detect
    codec            = 'h264',
    target_res       = '1080p',
    skip_sr          = False,
    skip_face        = False,              # set True if no faces in video
    dry_run_storage  = True,
)

"""---
## 📂 BATCH PIPELINE — Process a Full Directory
"""

def batch_pipeline(directory: str, **kwargs) -> list:
    """Process all videos in a folder. Passes all kwargs to full_pipeline."""
    jobs_input = upload_batch(directory)
    results = []
    for i, job in enumerate(jobs_input):
        print(f'\n[{i+1}/{len(jobs_input)}] Processing: {job["path"]}')
        try:
            # Re-run from preprocess (upload already done)
            job = preprocess_video(job)
            job = analyze_quality(job)
            job = run_filter_stage(job, kwargs.get('filter_mode'))
            job = run_enhancement_engine(
                      job,
                      enhance_mode=kwargs.get('enhance_mode','hd'),
                      skip_sr=kwargs.get('skip_sr', False),
                      skip_face=kwargs.get('skip_face', False))
            job = post_process(job,
                               codec=kwargs.get('codec','h264'),
                               target_res=kwargs.get('target_res','1080p'))
            job = upload_to_storage(job, dry_run=kwargs.get('dry_run_storage', True))
            generate_preview(job)
            job = evaluate_quality(job)
            job = prepare_publish_manifest(job)
            results.append(job)
        except Exception as e:
            print(f'❌ Failed: {job["path"]} — {e}')
    print(f'\n✅ Batch done: {len(results)}/{len(jobs_input)} succeeded')
    return results

# ── Run batch ────────────────────────────────────────────────────────
 results = batch_pipeline(
     directory    = 'my_videos/',
     enhance_mode = 'hd',
     skip_face    = False,
     target_res   = '1080p',
 )

"""---
## 📋 Quick Reference

### 🎛️ Parameters
| Param | Options | Notes |
|---|---|---|
| `enhance_mode` | `fast` / `hd` / `ultra` | fast=no SR, ultra=4x SR |
| `filter_mode` | `None` / `balanced` / `artifact` / `denoise` / `aggressive` | None=auto |
| `skip_sr` | `True/False` | Skip Real-ESRGAN |
| `skip_face` | `True/False` | Skip GFPGAN — set True for no-face videos |
| `codec` | `h264` / `h265` / `av1` | h264=fastest, av1=smallest file |
| `target_res` | `720p` / `1080p` / `4k` | |

### 🔑 APIs (fill keys in Stage 7)
| Service | Free Tier | Use For |
|---|---|---|
| Replicate | $1 credit | Cloud SR fallback |
| DeepAI | 100 calls/day | Waifu2x upscale |
| Cloudinary | 25GB/month | CDN + auto-transcode |

### ⚡ What was taken from enhance.py
- GFPGAN face restoration (2-stage AI pipeline)
- Parallel CPU multiprocessing pool
- `-movflags +faststart` for web streaming
- CRF 18 encode quality
- `tqdm` progress bars
- `warnings.filterwarnings` torchvision suppressor
- Batch directory processing
- `frame_%06d.png` naming (supports longer videos)

### 🔒 Security fixes applied vs enhance.py
- `eval()` on ffprobe replaced with `fractions.Fraction` (safe)
- Weights cached locally — no re-download on every run
"""